require('./lib/load-typescript.cjs');
const assert = require('node:assert/strict');
const {compileBlock} = require('../src/runtime/blockCompiler.ts');
const {defaultRoutine, validateRoutineSource} = require('../src/runtime/routine.ts');
const {RUNTIME_EXERCISES: catalog} = require('../src/runtime/exerciseCatalog.ts');
const {createRuntimeId} = require('../src/runtime/id.ts');
const source = {id:createRuntimeId(),userId:'10000000-0000-4000-8000-000000000001',version:1,goal:'hypertrophy',experience:'intermediate',daysPerWeek:4,sessionMinutes:60,equipment:['barbell','rack','bench','dumbbell','machine','cable','pullup_bar'],excludedExerciseIds:[],limitations:[],seedWorkingSets:[],createdAt:new Date().toISOString()};
const legacy = compileBlock(source);
assert.deepEqual(legacy.slots.map(x=>x.label),['upper.a','lower.a','upper.b','lower.b']);
const pplSource = {...source,routine:{...defaultRoutine(),split:'push_pull_legs'}};
const ppl = compileBlock(pplSource);
assert.deepEqual(ppl.slots.map(x=>x.label),['push','pull','legs']);
assert.equal(ppl.preferences.daysPerWeek,4);
const customSource = {...source,routine:{...defaultRoutine(),split:'custom',workouts:[{id:createRuntimeId(),name:'My push',exercises:[{exerciseId:'bench_press',sets:3,minReps:8,maxReps:12,targetRir:2,startingLoadKg:60}]}]}};
const custom = compileBlock(customSource);
assert.equal(custom.slots.length,1);
assert.equal(custom.slots[0].plannedExercises[0].prescription.startingLoadKg,60);
assert.throws(()=>validateRoutineSource({...customSource,routine:{...customSource.routine,workouts:[]}},catalog));
assert.throws(()=>validateRoutineSource({...customSource,routine:{...customSource.routine,progression:{...customSource.routine.progression,successfulSessions:0}}},catalog));
console.log('Routine model checks passed: independent splits, reported baselines, validation and unchanged legacy plans.');
const beforeEdit=JSON.stringify(custom);
const editedSource=structuredClone(customSource);
editedSource.version++;
editedSource.routine.workouts[0].name='Updated push';
editedSource.routine.workouts[0].exercises[0].sets=4;
const edited=compileBlock(editedSource,custom);
assert.notEqual(edited.id,custom.id);
assert.equal(edited.groupId,custom.groupId);
assert.equal(edited.slots[0].id,custom.slots[0].id);
assert.equal(JSON.stringify(custom),beforeEdit);
assert.equal(edited.slots[0].plannedExercises[0].sets,4);
console.log('Routine editing checks passed: immutable old revision and stable workout identity.');
const {nextRoutineSlot}=require('../src/runtime/sequence.ts');
const {previewRemainingWeek}=require('../src/runtime/remainingWeek.ts');
const {emptyRuntimeState}=require('../src/runtime/runtimePersistence.ts');
const {solveTrainingSession,commitRuntimeSession}=require('../src/runtime/runtimeService.ts');
const {planWeek}=require('../src/runtime/planDates.ts');
const ctx={date:'2026-09-21',minutesAvailable:60,recovery:'yes',unavailableEquipment:[],unavailableExerciseIds:[]};
let sequenceState={...emptyRuntimeState(),source:pplSource,block:{...ppl,startedOn:ctx.date}};
const forecast=previewRemainingWeek(sequenceState,[0,1,3,5].map(day=>({...ctx,date:`2026-09-${21+day}`})),ctx.date);
assert.deepEqual(forecast.plan.remainingWeek.windows.map(w=>w.slotId),[ppl.slots[0].id,ppl.slots[1].id,ppl.slots[2].id,ppl.slots[0].id]);
assert.equal(sequenceState.sessions.length,0);
for (const date of ['2026-09-21','2026-09-23','2026-09-28','2026-09-30']) {
  sequenceState=commitRuntimeSession(solveTrainingSession(sequenceState,{...ctx,date}));
}
assert.deepEqual(sequenceState.sessions.map(s=>s.slotId),forecast.plan.remainingWeek.windows.map(w=>w.slotId));
assert.equal(nextRoutineSlot(sequenceState.block,sequenceState.sessions,'2026-10-05').id,ppl.slots[1].id);
assert.equal(planWeek(sequenceState.block,'2026-11-09'),8);
console.log('Sequence checks passed: repeated types, missed days, week rollover, preview purity and ongoing routines.');
const {recordRuntimeSet,undoLastRuntimeSet,addRuntimeExercise,skipRemainingRuntimeSets,finishAndUpdateRoutine}=require('../src/runtime/runtimeService.ts');
const {toStoredTraining,fromStoredTraining}=require('../src/runtime/trainingState.ts');
let tracking={...emptyRuntimeState(),source:customSource,block:{...custom,startedOn:ctx.date}};
tracking=solveTrainingSession(tracking,ctx);
let entry=tracking.activeSession.exercises[0];
assert.equal(entry.exercise.id,'bench_press');
assert.equal(entry.sets.length,3);
assert.equal(entry.sets[0].loadKg,60);
assert.equal(entry.sets[0].maxReps,12);
const resultFor=(state,reps=10,weight=60)=>{const entry=state.activeSession.exercises.find(x=>x.sets.some(s=>s.status==='pending'));const set=entry.sets.find(s=>s.status==='pending');return {prescriptionId:state.activeSession.id,setId:set.id,exerciseId:entry.exercise.id,prescribedLoadKg:set.loadKg,prescribedMinReps:set.minReps,prescribedMaxReps:set.maxReps,targetRir:set.targetRir,actualLoadKg:weight,completedReps:reps,reportedRir:2,completedAt:new Date().toISOString()};};
tracking=recordRuntimeSet(tracking,resultFor(tracking));
assert.equal(tracking.setResults.length,1);
assert.equal(undoLastRuntimeSet(tracking).setResults.length,0);
tracking=addRuntimeExercise(tracking,{exerciseId:'biceps_curl',sets:2,minReps:10,maxReps:15,targetRir:2,startingLoadKg:7});
assert.equal(tracking.activeSession.exercises.length,2);
assert.equal(tracking.source.routine.workouts[0].exercises.length,1);
assert.deepEqual(fromStoredTraining(toStoredTraining(tracking)).activeSession,tracking.activeSession);
assert.throws(()=>addRuntimeExercise(tracking,{exerciseId:'biceps_curl',sets:2,minReps:10,maxReps:15,targetRir:2}));
const todayOnly=tracking.activeSession.id;
tracking=finishAndUpdateRoutine(skipRemainingRuntimeSets(tracking));
assert.equal(tracking.sessions.find(s=>s.id===todayOnly).status,'committed');
assert.equal(tracking.source.routine.workouts[0].exercises[0].sets,1);
assert(tracking.blockHistory.some(b=>b.id===custom.id));
console.log('Tracking checks passed: actuals, undo, temporary additions, persistence, explicit routine update and history.');
const {computeWeeklyStatus}=require('../src/runtime/status.ts');
let repeated={...emptyRuntimeState(),source:customSource,block:{...custom,startedOn:ctx.date}};
for(const date of ['2026-09-21','2026-09-23']) {
  repeated=solveTrainingSession(repeated,{...ctx,date});
  repeated=recordRuntimeSet(repeated,resultFor(repeated));
  repeated=commitRuntimeSession(skipRemainingRuntimeSets(repeated));
}
const progress=computeWeeklyStatus(repeated.block,repeated.sessions,repeated.setResults,1);
assert.equal(progress.sessionsLogged,2);
assert.equal(progress.totalSessions,4);
assert.equal(progress.muscles.find(x=>x.muscle==='chest').completedSets,2);
assert.equal(progress.muscles.find(x=>x.muscle==='triceps').completedSets,1);
assert.equal(progress.muscles.find(x=>x.muscle==='chest').scheduledSets,6);
console.log('Muscle progress checks passed: repeated occurrences, completed primary/secondary exposure and remaining forecasts.');
const {suggestWorkoutLoad}=require('../src/runtime/progression.ts');
let progressing={...emptyRuntimeState(),source:customSource,block:{...custom,startedOn:ctx.date}};
for(const date of ['2026-09-21','2026-09-23']) {
  progressing=solveTrainingSession(progressing,{...ctx,date});
  for(let i=0;i<3;i++) {
    assert.equal(progressing.activeSession.exercises[0].sets[i].loadKg,60);
    progressing=recordRuntimeSet(progressing,resultFor(progressing,12,60));
  }
  progressing=commitRuntimeSession(progressing);
}
const bench=catalog.find(x=>x.id==='bench_press');
const prescription=customSource.routine.workouts[0].exercises[0];
assert.equal(suggestWorkoutLoad(bench,prescription,customSource,progressing.sessions).loadKg,62.5);
assert.equal(suggestWorkoutLoad(bench,prescription,customSource,progressing.sessions.slice(0,1)).loadKg,60);
assert.equal(suggestWorkoutLoad(bench,{...prescription,maxReps:15},customSource,progressing.sessions).loadKg,60);
assert.equal(suggestWorkoutLoad(bench,prescription,{...customSource,routine:{...customSource.routine,progression:{...customSource.routine.progression,mode:'manual'}}},progressing.sessions).loadKg,60);
const missed=structuredClone(progressing.sessions);missed[1].exercises[0].sets[2].result.completedReps=8;
assert.equal(suggestWorkoutLoad(bench,prescription,customSource,missed).loadKg,60);
const skipped=structuredClone(progressing.sessions);skipped[1].exercises[0].sets[2].status='skipped';
assert.equal(suggestWorkoutLoad(bench,prescription,customSource,skipped).loadKg,60);
assert.equal(suggestWorkoutLoad(catalog.find(x=>x.id==='incline_db_press'),{...prescription,exerciseId:'incline_db_press',startingLoadKg:undefined},customSource,progressing.sessions).baselineKnown,false);
console.log('Progression checks passed: complete-session evidence, consecutive successes, manual mode, changed targets, skipped sets and separate exercise baselines.');
const {exerciseAlternatives}=require('../src/runtime/recommendations.ts');
const alternatives=exerciseAlternatives(bench,catalog,customSource,progressing.sessions,{...ctx,unavailableEquipment:['barbell']});
assert(alternatives.some(x=>x.exercise.id==='incline_db_press'));
assert(alternatives.every(x=>!x.exercise.equipment.includes('barbell')));
assert(alternatives.every(x=>x.exercise.primaryMuscles.includes('chest')));
assert(alternatives.find(x=>x.exercise.id==='incline_db_press').explanation.includes('Establish its own'));
const swapped=solveTrainingSession({...emptyRuntimeState(),source:customSource,block:custom},{...ctx,exerciseReplacements:{bench_press:'incline_db_press'}});
assert.equal(swapped.activeSession.exercises[0].exercise.id,'incline_db_press');
assert.equal(swapped.activeSession.exercises[0].sets[0].loadKg,0);
assert.equal(swapped.source.routine.workouts[0].exercises[0].exerciseId,'bench_press');
assert.throws(()=>solveTrainingSession({...emptyRuntimeState(),source:customSource,block:custom},{...ctx,exerciseReplacements:{bench_press:'biceps_curl'}}));
console.log('Recommendation checks passed: history explanations, equipment filters, explicit acceptance and no transferred weight.');
const {applyRemainingWeek}=require('../src/runtime/remainingWeek.ts');
const scheduledBase={...emptyRuntimeState(),source:customSource,block:{...custom,startedOn:ctx.date}};
const accepted=applyRemainingWeek(scheduledBase,previewRemainingWeek(scheduledBase,[ctx],ctx.date));
const changedToday=solveTrainingSession(accepted,{...ctx,exerciseReplacements:{bench_press:'incline_db_press'}});
assert.equal(changedToday.activeSession.exercises[0].exercise.id,'incline_db_press');
assert.equal(changedToday.activeSession.exercises[0].needsBaseline,true);
const missedSchedule=applyRemainingWeek({...emptyRuntimeState(),source:pplSource,block:{...ppl,startedOn:ctx.date}},forecast);
assert.equal(solveTrainingSession(missedSchedule,{...ctx,date:'2026-09-22'}).activeSession.slotId,ppl.slots[0].id);
const emptySchedule=applyRemainingWeek(scheduledBase,previewRemainingWeek(scheduledBase,[],ctx.date));
assert.throws(()=>solveTrainingSession(emptySchedule,ctx));
assert.equal(solveTrainingSession(emptySchedule,{...ctx,extraWorkout:true}).activeSession.slotId,custom.slots[0].id);
console.log('Schedule override checks passed: explicit substitutions after acceptance, missed windows and extra workouts.');
const {createRuntimePersistence}=require('../src/runtime/runtimePersistence.ts');
(async()=>{
  let device=null,online=false;
  let cloud={revision:0,mutationId:null,state:null};
  const adapters={createId:createRuntimeId,readLocal:async()=>structuredClone(device),writeLocal:async value=>{device=structuredClone(value)},backup:async()=>{},
    readRemote:async()=>{if(!online)throw Error('offline');return structuredClone(cloud)},
    writeRemote:async(state,revision,mutationId)=>{if(!online)throw Error('offline');if(revision!==cloud.revision)return {revision:cloud.revision,conflict:true};cloud={revision:revision+1,mutationId,state:structuredClone(state)};return {revision:cloud.revision,conflict:false}}};
  const first=createRuntimePersistence(adapters);
  await first.load();
  await first.stage(progressing);
  await first.flush();
  const restarted=createRuntimePersistence(adapters);
  const loaded=await restarted.load();
  assert.deepEqual(loaded.state.source.routine,customSource.routine);
  assert.equal(loaded.state.setResults.length,6);
  online=true;await restarted.flush();
  assert.deepEqual(cloud.state.source.routine,customSource.routine);
  assert.equal(cloud.state.sessions.length,2);
  console.log('Routine offline checks passed: restart retains pending routine and actuals; retry saves them to the cloud adapter.');
})().catch(error=>{console.error(error);process.exitCode=1});

const {startUnplannedWorkout}=require('../src/runtime/freeWorkout.ts');
const {scheduledOccurrences}=require('../src/runtime/sequence.ts');
const emptyLog=emptyRuntimeState(), emptyLogSnapshot=JSON.stringify(emptyLog);
let quick=startUnplannedWorkout(emptyLog,source,'bench_press');
assert.equal(JSON.stringify(emptyLog),emptyLogSnapshot);
assert.equal(quick.block.kind,'workout');
assert.equal(quick.activeSession.exercises[0].exercise.id,'bench_press');
assert.equal(quick.activeSession.exercises[0].needsBaseline,true);
assert.equal(quick.setResults.length,0);
assert.throws(()=>startUnplannedWorkout(quick,source,'cable_row'));
quick=recordRuntimeSet(quick,resultFor(quick,10,40));
quick=commitRuntimeSession(skipRemainingRuntimeSets(quick));
assert.equal(scheduledOccurrences(quick.block,quick.sessions,1).length,0);
const restoredQuick=fromStoredTraining(toStoredTraining(quick));
assert.equal(restoredQuick.block.kind,'workout');assert.equal(restoredQuick.setResults.length,1);
const oldQuick=JSON.stringify(restoredQuick);
const nextQuick=startUnplannedWorkout(restoredQuick,source,'cable_row');
assert.equal(JSON.stringify(restoredQuick),oldQuick);
assert.equal(nextQuick.sessions.length,2);assert.equal(nextQuick.setResults.length,1);
assert(nextQuick.blockHistory.some(b=>b.id===restoredQuick.block.id));
assert.throws(()=>startUnplannedWorkout({...emptyRuntimeState(),source:customSource,block:custom},source,'bench_press'));
assert.throws(()=>startUnplannedWorkout(emptyLog,{...source,excludedExerciseIds:['bench_press']},'bench_press'));
console.log('Unplanned workouts: explicit start, unset baseline, immutable history, no recurring forecast, restored logs and plan protection passed.');

{
const {startAdditionalWorkout,repeatWorkoutExercises}=require('../src/runtime/freeWorkout.ts');
const plannedState={...emptyRuntimeState(),source:customSource,block:custom};
const plannedSnapshot=JSON.stringify(plannedState);
let additional=startAdditionalWorkout(plannedState,source,[{exerciseId:'bench_press',sets:2,minReps:8,maxReps:12,targetRir:2}],'Extra push');
assert.equal(JSON.stringify(plannedState),plannedSnapshot);
assert.deepEqual(additional.block,custom);assert.deepEqual(additional.source,customSource);
assert(!custom.slots.some(s=>s.id===additional.activeSession.slotId));
assert.equal(additional.activeSession.name,'Extra push');assert.equal(additional.setResults.length,0);
assert.throws(()=>startAdditionalWorkout(additional,source,[]));
additional=recordRuntimeSet(additional,resultFor(additional,10,40));
additional=commitRuntimeSession(skipRemainingRuntimeSets(additional));
const finishedExtra=additional.sessions.at(-1);
const nextBefore=nextRoutineSlot(custom,plannedState.sessions).id;
assert.equal(nextRoutineSlot(custom,additional.sessions).id,nextBefore);
const repeatItems=repeatWorkoutExercises(finishedExtra);assert.equal(repeatItems[0].sets,1);
const repeated=startAdditionalWorkout(additional,source,repeatItems,'Extra push');
assert.notEqual(repeated.activeSession.id,finishedExtra.id);
assert(repeated.activeSession.exercises.every(e=>e.sets.every(s=>s.status==='pending'&&!s.result)));
assert.deepEqual(repeated.setResults,additional.setResults);
assert.equal(fromStoredTraining(toStoredTraining(repeated)).activeSession.name,'Extra push');
assert.throws(()=>startAdditionalWorkout(plannedState,source,[]));
assert.throws(()=>startAdditionalWorkout(plannedState,source,[{exerciseId:'missing',sets:3,minReps:8,maxReps:12,targetRir:2}]));
assert.throws(()=>startAdditionalWorkout({...plannedState,source:{...customSource,excludedExerciseIds:['bench_press']}},source,repeatItems));
const freshAdditional=startAdditionalWorkout(emptyRuntimeState(),source,repeatItems);
assert.equal(freshAdditional.block.kind,'workout');assert.equal(freshAdditional.activeSession.exercises.length,1);
const {finishAndSaveNewWorkout}=require('../src/runtime/freeWorkout.ts');
const readyToSave=skipRemainingRuntimeSets(recordRuntimeSet(repeated,resultFor(repeated,10,40)));
const savedRoutine=finishAndSaveNewWorkout(readyToSave);
assert.equal(savedRoutine.activeSession,null);
assert.equal(savedRoutine.source.routine.workouts.length,customSource.routine.workouts.length+1);
assert.deepEqual(savedRoutine.source.routine.workouts[0],customSource.routine.workouts[0]);
assert(savedRoutine.blockHistory.some(b=>b.id===custom.id));
assert.deepEqual(savedRoutine.setResults,readyToSave.setResults);
const savedFirst=finishAndSaveNewWorkout(skipRemainingRuntimeSets(recordRuntimeSet(freshAdditional,resultFor(freshAdditional,10,40))));
assert.notEqual(savedFirst.block.kind,'workout');
assert.equal(savedFirst.source.routine.workouts.length,1);
assert.equal(fromStoredTraining(toStoredTraining(savedFirst)).sessions.length,1);
console.log('Additional/repeated workouts preserve saved routines, sequence, history and fresh pending set IDs; constraints and restart verified.');

}
