#!/usr/bin/env python3
"""Compile the editable v7 SVG into native highlight paths and a review page.

No artwork pixels are modified. Edit the source SVG, then rerun this script.
Run with --check to verify the committed/generated artifacts match the source.
"""
from pathlib import Path
import argparse
import html
import json
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'assets/images/muscle-map/athlete-back-v7-regions.svg'
OUTPUT = ROOT / 'src/screens/runtime/backMuscleContours.ts'
REVIEW = ROOT / 'scripts/muscle-map/review/back-v7.html'


def build():
    svg = ET.parse(SOURCE).getroot()
    x, y, width, height = map(int, svg.attrib['viewBox'].split())
    assert (x, y, width, height) == (0, 0, 1084, 1451)
    paths = list(svg.findall('{http://www.w3.org/2000/svg}path'))
    ids = [p.attrib['id'] for p in paths]
    assert len(ids) == len(set(ids)), 'duplicate region IDs'
    masks = []
    for p in paths:
        a = p.attrib
        assert a['d'].rstrip().endswith('Z'), f"open region: {a['id']}"
        if a.get('data-reference-only') == 'true':
            continue
        masks.append(dict(muscle=a['data-muscle'], part=a['id'], label=a['data-label'],
                          visible=a['d'], hit=a['d'],
                          **({'covered': True} if a.get('data-covered') == 'true' else {})))
    output = """// GENERATED by scripts/muscle-map/build_back_regions.py.
// Edit assets/images/muscle-map/athlete-back-v7-regions.svg, then regenerate.
// Registered to the unmodified athlete-back-v7.png in native 1084 × 1451 pixels.
// These are reviewed surface projections; covered regions indicate location only.
import type { MuscleMask } from './muscleMasks';

export const BACK_MUSCLE_MAP_SIZE = { width: 1084, height: 1451 } as const;

export const BACK_MUSCLE_CONTOURS: MuscleMask[] = """ + json.dumps(masks, indent=2) + ";\n\n"
    output += """// Group highlights reuse the exact part geometry, keeping touch/visible boundaries aligned.
export const BACK_GROUP_CONTOURS: MuscleMask[] = (['back', 'hamstrings'] as const).map(muscle => {
  const visible = BACK_MUSCLE_CONTOURS.filter(mask => mask.muscle === muscle).map(mask => mask.visible).join(' ');
  return { muscle, part: muscle, label: muscle === 'back' ? 'Back' : 'Hamstrings', visible, hit: visible };
});
"""
    options = ''.join(f'<option value="{p.attrib["id"]}">{html.escape(p.attrib["data-label"])}</option>' for p in paths)
    overlay = '\n'.join(f'<path id="{p.attrib["id"]}" data-group="{p.attrib["data-muscle"]}" fill="{p.attrib["fill"]}" d="{p.attrib["d"]}"><title>{html.escape(p.attrib["data-label"])}</title></path>' for p in paths)
    review = f"""<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>FitArc — back v7 highlight review</title>
<style>
*{{box-sizing:border-box}} body{{margin:0;background:#08090b;color:#eee;font:15px system-ui}}
header{{padding:20px;max-width:960px;margin:auto}}h1{{font-size:23px;margin:0 0 8px}}p{{color:#aaa;line-height:1.5}}
.controls{{display:flex;gap:14px;align-items:center;flex-wrap:wrap}}select,button{{padding:9px;background:#191c23;color:#fff;border:1px solid #353945;border-radius:8px}}
label{{display:flex;align-items:center;gap:8px}}main{{max-width:960px;margin:auto}}svg{{display:block;width:100%;max-height:82vh;background:#000}}
.reference{{padding:20px}}.reference img{{max-width:100%;width:480px}}path{{cursor:pointer;stroke:#fff;stroke-width:1.5;stroke-opacity:.65}}
a{{color:#f5893c}}:focus-visible{{outline:2px solid #f5893c}}
</style>
<header><h1>Back #7 — highlight alignment</h1><p>Original artwork plus editable SVG regions. Select a region or tap it. Glutes indicate location beneath shorts; forearms are reference-only. These shapes are not a clinical anatomy atlas.</p>
<div class="controls"><select id="part" aria-label="Muscle region"><option value="all">All regions</option>{options}</select>
<label>Opacity <input id="opacity" type="range" min="0" max="1" step="0.05" value="0.45"></label>
<label><input id="art" type="checkbox" checked>Artwork</label>
<button id="zoom">Zoom upper body</button><button id="reset">Full body</button></div></header>
<main><svg id="map" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" role="img" aria-label="Back athlete with muscle highlight regions">
<image id="athlete" href="../../../assets/images/muscle-map/athlete-back-v7.png" width="{width}" height="{height}"/>
<g id="regions" opacity="0.45">{overlay}</g></svg>
<details class="reference"><summary>Original user guide and tracing notes</summary>
<p>The guide supplied the intended regions. Boundaries were manually registered to #7, ignoring label lines. Trapezius covers the rhomboids; the guide's mismatched labels were not carried over. Hamstrings are represented as outer and inner surface regions. Calf heads are separated, with soleus only along the visible sides. The central Achilles area is excluded.</p>
<img src="../references/back-colored-guide.jpeg" alt="Original labeled color guide">
<p><a href="../../../assets/images/muscle-map/athlete-back-v7-regions.svg">Editable SVG source</a></p></details></main>
<script>
const part=document.querySelector('#part'),regions=document.querySelector('#regions'),map=document.querySelector('#map');
function select(id){{part.value=id;regions.querySelectorAll('path').forEach(p=>p.style.display=id==='all'||id===p.id?'':'none')}}
part.onchange=()=>select(part.value);
regions.querySelectorAll('path').forEach(p=>p.onclick=()=>select(p.id));
document.querySelector('#opacity').oninput=e=>regions.setAttribute('opacity',e.target.value);
document.querySelector('#art').onchange=e=>document.querySelector('#athlete').style.display=e.target.checked?'':'none';
document.querySelector('#zoom').onclick=()=>map.setAttribute('viewBox','290 175 510 420');
document.querySelector('#reset').onclick=()=>map.setAttribute('viewBox','0 0 {width} {height}');
</script></html>
"""
    # The app geometry is traced from the artwork by trace_back_v7.py (these guides only seed it), so only the
    # review page is produced here; regenerate backMuscleContours.ts with trace_back_v7.py.
    return {REVIEW: review}


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in build().items():
        if args.check:
            assert path.exists() and path.read_text() == content, f'Stale artifact: {path}'
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        print(('checked ' if args.check else 'wrote ') + str(path.relative_to(ROOT)))
