-- Retired during the explicitly chosen fresh start (2026-09-24).
-- This no-op keeps the already-deployed version in the migration ledger while allowing
-- an empty database to replay the new baseline without missing legacy exercise tables.
-- Original SQL is preserved in ../legacy/202609170001_training_runtime.sql for reference.
-- Existing installations are cleaned by 202609240003_retire_legacy_training.sql.
